steps:

  - name: 'gcr.io/$PROJECT_ID/restore_cache'
  args:
    - '--bucket=gs://$_CACHE_BUCKET/'
    - '--key=resources-$( checksum package-lock.json )'

  - name: node
    entrypoint: npm
    args: ['install']
    
  - name: node
    entrypoint: npm
    args: ['run', 'test-ci']

  - name: 'gcr.io/$PROJECT_ID/save_cache'
  args:
    - '--bucket=gs://$_CACHE_BUCKET/'
    - '--key=resources-$( checksum package-lock.json )'
    - '--path=node_modules'
    - '--no-clobber'